kafka:
  brokers: "127.0.0.1:9092"
  consumer-count:
    card-content: 1
  topic:
    card-content: "testTopic"

camel:
  kafka:
    manual-commit: "autoCommitEnable=false&autoCommitOnStop=none&autoOffsetReset=earliest"
    from:
      card-content: "kafka:${kafka.topic.card-content}?brokers=${kafka.brokers}&groupId=card&consumersCount=${kafka.consumer-count.card-content}&${camel.kafka.manual-commit}"

  jdbc:
    to:
      tamount: "jdbc:myDataSource"